import jsPDF from 'jspdf';

interface CategoryPrediction {
  title: string;
  prediction: string;
  palmFeatures?: string[];
  planetaryInfluence?: string;
  timeline?: string;
  guidance: string;
  rating: number;
}

interface PalmAnalysis {
  language?: string;
  palmType?: string;
  dominantPlanet?: string;
  nakshatra?: string;
  greeting?: string;
  overallDestiny?: string;
  categories?: {
    career?: CategoryPrediction;
    love?: CategoryPrediction;
    health?: CategoryPrediction;
    family?: CategoryPrediction;
    education?: CategoryPrediction;
    spiritual?: CategoryPrediction;
    travel?: CategoryPrediction;
  };
  luckyElements?: {
    colors?: string[];
    gemstones?: string[];
    mantras?: string[];
    days?: string[];
    numbers?: number[];
    metals?: string[];
    directions?: string[];
  };
  remedies?: string[];
  blessings?: string;
}

const CATEGORY_ICONS: Record<string, string> = {
  career: '💼',
  love: '❤️',
  health: '💪',
  family: '👨‍👩‍👧‍👦',
  education: '🎓',
  spiritual: '🕉️',
  travel: '✈️'
};

const CATEGORY_TITLES: Record<string, { hi: string; en: string }> = {
  career: { hi: 'करियर एवं धन', en: 'Career & Finance' },
  love: { hi: 'प्रेम एवं रिश्ते', en: 'Love & Relationships' },
  health: { hi: 'स्वास्थ्य एवं शक्ति', en: 'Health & Vitality' },
  family: { hi: 'परिवार एवं संतान', en: 'Family & Children' },
  education: { hi: 'शिक्षा एवं ज्ञान', en: 'Education & Wisdom' },
  spiritual: { hi: 'आध्यात्मिक विकास', en: 'Spiritual Growth' },
  travel: { hi: 'यात्रा एवं भाग्य', en: 'Travel & Fortune' }
};

export const generatePalmReadingPDF = (analysis: PalmAnalysis, userName?: string): void => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = margin;

  // Colors
  const primaryColor: [number, number, number] = [255, 102, 0]; // Saffron
  const secondaryColor: [number, number, number] = [128, 0, 128]; // Purple
  const textColor: [number, number, number] = [51, 51, 51];
  const mutedColor: [number, number, number] = [128, 128, 128];

  // Helper function to add wrapped text
  const addWrappedText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number): number => {
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return y + (lines.length * lineHeight);
  };

  // Helper to check page break
  const checkPageBreak = (neededSpace: number): void => {
    if (yPos + neededSpace > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
  };

  // ========== HEADER ==========
  // Gradient-like background
  doc.setFillColor(255, 243, 224);
  doc.rect(0, 0, pageWidth, 50, 'F');
  
  // Om symbol
  doc.setFontSize(28);
  doc.setTextColor(255, 102, 0);
  doc.text('🕉️', pageWidth / 2 - 5, 15, { align: 'center' });

  // Title
  doc.setFontSize(22);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Guru Palm Reading Report', pageWidth / 2, 28, { align: 'center' });

  // Subtitle
  doc.setFontSize(10);
  doc.setTextColor(...mutedColor);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by BhaktVerse • ${new Date().toLocaleDateString('en-IN', { 
    day: 'numeric', 
    month: 'long', 
    year: 'numeric' 
  })}`, pageWidth / 2, 36, { align: 'center' });

  // User info line
  if (userName || analysis.palmType) {
    doc.setFontSize(11);
    doc.setTextColor(...textColor);
    const infoText = [
      userName ? `Name: ${userName}` : '',
      analysis.palmType ? `Palm Type: ${analysis.palmType}` : '',
      analysis.dominantPlanet ? `Dominant Planet: ${analysis.dominantPlanet}` : ''
    ].filter(Boolean).join(' • ');
    doc.text(infoText, pageWidth / 2, 44, { align: 'center' });
  }

  yPos = 55;

  // ========== AI GURU GREETING ==========
  if (analysis.greeting) {
    checkPageBreak(30);
    
    doc.setFillColor(255, 248, 240);
    doc.roundedRect(margin, yPos, contentWidth, 25, 3, 3, 'F');
    doc.setDrawColor(255, 153, 51);
    doc.roundedRect(margin, yPos, contentWidth, 25, 3, 3, 'S');
    
    doc.setFontSize(9);
    doc.setTextColor(...secondaryColor);
    doc.setFont('helvetica', 'bold');
    doc.text('🙏 AI GURU\'S BLESSING', margin + 5, yPos + 6);
    
    doc.setFontSize(10);
    doc.setTextColor(...textColor);
    doc.setFont('helvetica', 'italic');
    const greetingLines = doc.splitTextToSize(`"${analysis.greeting}"`, contentWidth - 10);
    doc.text(greetingLines, margin + 5, yPos + 14);
    
    yPos += 30;
  }

  // ========== OVERALL DESTINY ==========
  if (analysis.overallDestiny) {
    checkPageBreak(40);
    
    doc.setFontSize(12);
    doc.setTextColor(...primaryColor);
    doc.setFont('helvetica', 'bold');
    doc.text('⭐ Your Life Path', margin, yPos + 5);
    
    yPos += 10;
    doc.setFontSize(10);
    doc.setTextColor(...textColor);
    doc.setFont('helvetica', 'normal');
    yPos = addWrappedText(analysis.overallDestiny, margin, yPos, contentWidth, 5);
    yPos += 8;
  }

  // ========== CATEGORY PREDICTIONS ==========
  if (analysis.categories) {
    checkPageBreak(20);
    
    doc.setFontSize(14);
    doc.setTextColor(...primaryColor);
    doc.setFont('helvetica', 'bold');
    doc.text('📊 Detailed Category Predictions', margin, yPos);
    yPos += 8;

    Object.entries(analysis.categories).forEach(([key, category]) => {
      if (!category) return;

      const neededSpace = 50 + (category.prediction.length / 80) * 5;
      checkPageBreak(neededSpace);

      // Category header box
      doc.setFillColor(248, 248, 255);
      doc.roundedRect(margin, yPos, contentWidth, 12, 2, 2, 'F');
      
      const icon = CATEGORY_ICONS[key] || '📌';
      const title = CATEGORY_TITLES[key] || { hi: key, en: key };
      
      doc.setFontSize(11);
      doc.setTextColor(...secondaryColor);
      doc.setFont('helvetica', 'bold');
      doc.text(`${icon} ${title.en} (${title.hi})`, margin + 3, yPos + 8);
      
      // Rating
      doc.setFontSize(10);
      doc.setTextColor(255, 102, 0);
      doc.text(`Rating: ${category.rating}/10`, pageWidth - margin - 25, yPos + 8);
      
      yPos += 15;

      // Prediction text
      doc.setFontSize(9);
      doc.setTextColor(...textColor);
      doc.setFont('helvetica', 'normal');
      yPos = addWrappedText(category.prediction, margin + 3, yPos, contentWidth - 6, 4.5);
      
      // Timeline
      if (category.timeline) {
        yPos += 2;
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(100, 100, 100);
        doc.text('Timeline: ', margin + 3, yPos);
        doc.setFont('helvetica', 'normal');
        doc.text(category.timeline, margin + 25, yPos);
        yPos += 4;
      }

      // Guidance
      if (category.guidance) {
        yPos += 2;
        doc.setFillColor(232, 245, 233);
        const guidanceLines = doc.splitTextToSize(`💡 Guidance: ${category.guidance}`, contentWidth - 10);
        doc.roundedRect(margin + 2, yPos - 3, contentWidth - 4, guidanceLines.length * 4 + 4, 2, 2, 'F');
        doc.setFontSize(8);
        doc.setTextColor(46, 125, 50);
        doc.text(guidanceLines, margin + 5, yPos + 1);
        yPos += guidanceLines.length * 4 + 6;
      }

      yPos += 5;
    });
  }

  // ========== LUCKY ELEMENTS ==========
  if (analysis.luckyElements) {
    checkPageBreak(50);
    
    doc.setFontSize(14);
    doc.setTextColor(...primaryColor);
    doc.setFont('helvetica', 'bold');
    doc.text('🍀 Lucky Elements', margin, yPos);
    yPos += 10;

    const elements = [
      { label: '🎨 Colors', values: analysis.luckyElements.colors },
      { label: '💎 Gemstones', values: analysis.luckyElements.gemstones },
      { label: '📅 Days', values: analysis.luckyElements.days },
      { label: '🔢 Numbers', values: analysis.luckyElements.numbers?.map(String) },
      { label: '🧭 Directions', values: analysis.luckyElements.directions },
      { label: '⚗️ Metals', values: analysis.luckyElements.metals },
    ];

    const colWidth = contentWidth / 2;
    let col = 0;
    let rowY = yPos;

    elements.forEach((elem, i) => {
      if (!elem.values || elem.values.length === 0) return;

      const x = margin + (col * colWidth);
      
      doc.setFontSize(9);
      doc.setTextColor(...secondaryColor);
      doc.setFont('helvetica', 'bold');
      doc.text(elem.label, x, rowY);
      
      doc.setFontSize(9);
      doc.setTextColor(...textColor);
      doc.setFont('helvetica', 'normal');
      doc.text(elem.values.join(', '), x, rowY + 5);

      col++;
      if (col >= 2) {
        col = 0;
        rowY += 14;
      }
    });

    yPos = rowY + 10;
  }

  // ========== MANTRAS ==========
  if (analysis.luckyElements?.mantras && analysis.luckyElements.mantras.length > 0) {
    checkPageBreak(40);

    doc.setFillColor(255, 243, 224);
    doc.roundedRect(margin, yPos, contentWidth, 8 + analysis.luckyElements.mantras.length * 6, 3, 3, 'F');
    doc.setDrawColor(255, 153, 51);
    doc.roundedRect(margin, yPos, contentWidth, 8 + analysis.luckyElements.mantras.length * 6, 3, 3, 'S');

    doc.setFontSize(11);
    doc.setTextColor(...primaryColor);
    doc.setFont('helvetica', 'bold');
    doc.text('🕉️ Recommended Mantras', margin + 5, yPos + 6);

    yPos += 12;
    doc.setFontSize(10);
    doc.setTextColor(...textColor);
    doc.setFont('helvetica', 'normal');
    analysis.luckyElements.mantras.forEach(mantra => {
      doc.text(`• ${mantra}`, margin + 8, yPos);
      yPos += 6;
    });
    yPos += 5;
  }

  // ========== REMEDIES ==========
  if (analysis.remedies && analysis.remedies.length > 0) {
    checkPageBreak(40);

    doc.setFontSize(12);
    doc.setTextColor(...secondaryColor);
    doc.setFont('helvetica', 'bold');
    doc.text('🔱 Spiritual Remedies', margin, yPos);
    yPos += 7;

    doc.setFontSize(9);
    doc.setTextColor(...textColor);
    doc.setFont('helvetica', 'normal');
    analysis.remedies.forEach(remedy => {
      const lines = doc.splitTextToSize(`• ${remedy}`, contentWidth - 5);
      doc.text(lines, margin + 3, yPos);
      yPos += lines.length * 4.5;
    });
    yPos += 5;
  }

  // ========== BLESSINGS ==========
  if (analysis.blessings) {
    checkPageBreak(30);

    doc.setFillColor(232, 245, 233);
    doc.roundedRect(margin, yPos, contentWidth, 20, 3, 3, 'F');
    doc.setDrawColor(76, 175, 80);
    doc.roundedRect(margin, yPos, contentWidth, 20, 3, 3, 'S');

    doc.setFontSize(10);
    doc.setTextColor(46, 125, 50);
    doc.setFont('helvetica', 'bold');
    doc.text('🙏 Final Blessings', margin + 5, yPos + 6);

    doc.setFont('helvetica', 'italic');
    const blessingLines = doc.splitTextToSize(`"${analysis.blessings}"`, contentWidth - 10);
    doc.text(blessingLines, margin + 5, yPos + 12);
    yPos += 25;
  }

  // ========== FOOTER ==========
  checkPageBreak(20);
  
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, pageHeight - 20, pageWidth - margin, pageHeight - 20);

  doc.setFontSize(8);
  doc.setTextColor(...mutedColor);
  doc.setFont('helvetica', 'normal');
  doc.text('🕉️ This report was generated by BhaktVerse AI Guru Palm Reading System', pageWidth / 2, pageHeight - 14, { align: 'center' });
  doc.text('For spiritual guidance & entertainment purposes only • www.bhaktverse.com', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save the PDF
  const fileName = `BhaktVerse-Palm-Reading-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};
