-- Insert comprehensive saints data
INSERT INTO saints (name, tradition, biography, key_teachings, famous_quotes, birth_year, death_year, primary_language, image_url, verified, ai_model_fine_tuned, personality_traits) VALUES
-- Hindu Saints and Gurus
('Swami Vivekananda', 'Vedanta', 'Swami Vivekananda was a Hindu monk and philosopher who introduced Vedanta and Yoga to the Western world. He was a chief disciple of the 19th-century Indian mystic Ramakrishna Paramahaṃsa and the founder of the Ramakrishna Math and the Ramakrishna Mission.', 'Arise, awake, and stop not until the goal is reached. Be strong, be fearless, be practical. Religion is realization; not talk, nor doctrine, nor theories.', '["Arise, awake, and stop not until the goal is reached!", "You are the children of God, the sharers of immortal bliss.", "Take up one idea. Make that one idea your life.", "Be strong! Be fearless! Be beautiful! And believe that anything is possible."]', 1863, 1902, 'hi', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face', true, true, '{"wisdom": "profound", "personality": "inspiring", "approach": "practical", "focus": "youth_empowerment"}'),

('Sant Kabir Das', 'Bhakti', 'Kabir was a 15th-century Indian mystic poet and saint whose writings influenced Hinduism and Islam. His poetry is characterized by its simple language and universal spiritual themes, emphasizing the unity of all religions and direct experience of the divine.', 'Unity of all religions, importance of devotion over ritual, direct experience of divine. Truth is one, paths are many. God dwells within every heart.', '["काल करे सो आज कर, आज करे सो अब। पल में प्रलय होएगी, बहुरि करेगा कब॥", "सुनो भाई साधो, सब संसार है सपना।", "जहाँ दया तहाँ धर्म है, जहाँ लोभ वहाँ पाप।", "बड़ा हुआ तो क्या हुआ जैसे पेड़ खजूर। पंथी को छाया नहीं फल लागे अति दूर॥"]', 1440, 1518, 'hi', 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=400&h=400&fit=crop&crop=face', true, true, '{"wisdom": "simple", "personality": "humble", "approach": "direct", "focus": "unity"}'),

('Meera Bai', 'Krishna Bhakti', 'Meera Bai was a 16th-century Hindu mystic poet and devotee of Lord Krishna. Born into royalty, she renounced worldly pleasures to dedicate her life to Krishna worship, composing devotional songs that are still sung today.', 'Devotional love (bhakti) as the path to liberation, surrender to divine will, pure love transcends all social barriers. Krishna is the supreme beloved.', '["मेरे तो गिरिधर गोपाल, दूसरो न कोई।", "जो वादा सो निबाहना पड़ेगा।", "हरि आप हरो जन री भीर।", "राणा जी मैं तो राम के गुण गाऊंगी।"]', 1498, 1547, 'hi', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face', true, true, '{"wisdom": "devotional", "personality": "surrendering", "approach": "emotional", "focus": "krishna_bhakti"}'),

('Adi Shankaracharya', 'Advaita Vedanta', 'Adi Shankara was an 8th-century Indian philosopher and theologian who consolidated the doctrine of Advaita Vedanta. He established four major monasteries (mathas) in India and wrote extensive commentaries on the Upanishads, Brahma Sutras, and Bhagavad Gita.', 'Non-dualism (Advaita), Brahman is the ultimate reality, the individual soul (Atman) and universal soul (Brahman) are one. Knowledge of the Self leads to liberation.', '["ब्रह्म सत्यं जगन्मिथ्या, जीवो ब्रह्मैव नापर:।", "आत्मा वा अरे द्रष्टव्यः श्रोतव्यो मन्तव्यो निदिध्यासितव्यः।", "सर्वम् खल्विदम् ब्रह्म।", "अहम् ब्रह्मास्मि।"]', 788, 820, 'sa', 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&h=400&fit=crop&crop=face', true, true, '{"wisdom": "philosophical", "personality": "intellectual", "approach": "logical", "focus": "non_dualism"}'),

('Tulsidas', 'Ramayana Tradition', 'Tulsidas was a 16th-century Hindu poet-saint famous for authoring the epic Ramcharitmanas, a retelling of the Ramayana in Awadhi. He is considered one of the greatest poets in Hindi literature and a devoted follower of Lord Rama.', 'Devotion to Rama as the supreme deity, the power of divine name (nama), importance of dharma and righteousness. Service to God through seva and bhakti.', '["राम नाम मनि दीप धरु जीह देहरीं द्वार।", "तुलसी साथी विपत्ति के, विद्या विनय विवेक।", "कष्ट न दै कहु काहि को, राम बिनु रहे न कोय।", "रघुपति राघव राजा राम, पतित पावन सीता राम।"]', 1532, 1623, 'hi', 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=400&h=400&fit=crop&crop=face', true, true, '{"wisdom": "devotional", "personality": "humble", "approach": "narrative", "focus": "rama_bhakti"}'),

('Guru Nanak Dev Ji', 'Sikhism', 'Guru Nanak was the founder of Sikhism and the first of the ten Sikh Gurus. He taught the oneness of God, equality of all humans, and the importance of honest living and service to others. His teachings form the foundation of Sikh philosophy.', 'One God (Ik Onkar), equality of all humans regardless of caste or creed, honest living (kirat karni), sharing with others (vand chakna), meditation on Gods name (naam japna).', '["एक ओंकार सतिनाम करता पुरखु।", "सर्बत दा भला।", "किरत करो, नाम जपो, वंड छको।", "जो दीसै सो तो नाही, है कछु गुपत गुदाम।"]', 1469, 1539, 'pa', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face', true, true, '{"wisdom": "universal", "personality": "compassionate", "approach": "practical", "focus": "social_equality"}'),

-- Contemporary Spiritual Leaders
('Paramahansa Yogananda', 'Kriya Yoga', 'Paramahansa Yogananda was an Indian monk and yogi who introduced millions to the teachings of meditation and Kriya Yoga through his organization Self-Realization Fellowship. His book "Autobiography of a Yogi" is a spiritual classic.', 'Kriya Yoga as the fastest path to God-realization, direct personal experience of God, harmony of all religions, meditation as the way to find God within.', '["The season of failure is the best time for sowing the seeds of success.", "Be as simple as you can be; you will be astonished to see how uncomplicated and happy your life can become.", "Calmness is the ideal state in which we should receive all lifes experiences.", "Change yourself and you have done your part in changing the world."]', 1893, 1952, 'en', 'https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=400&h=400&fit=crop&crop=face', true, true, '{"wisdom": "scientific", "personality": "joyful", "approach": "methodical", "focus": "kriya_yoga"}'),

('Ramana Maharshi', 'Self-Enquiry', 'Ramana Maharshi was a 20th-century Indian sage known for his method of self-enquiry and his teachings on Self-realization. He taught that the Self is the only reality and emphasized the question "Who am I?" as the direct path to enlightenment.', 'Self-enquiry (Atma vichara) through the question "Who am I?", the Self is pure awareness, all suffering comes from identification with the ego, surrender to the Self.', '["Your own Self-realization is the greatest service you can render the world.", "Who am I? is the only investigation which will lead to the unfolding of the truth.", "Happiness is your nature. It is not wrong to desire it.", "The degree of freedom from unwanted thoughts and the degree of concentration on a single thought are the measures to gauge spiritual progress."]', 1879, 1950, 'ta', 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face', true, true, '{"wisdom": "direct", "personality": "silent", "approach": "inquiry", "focus": "self_realization"}');

-- Insert scriptures data
INSERT INTO scriptures (title, author, tradition, language, type, total_chapters, description, summary, difficulty_level, estimated_reading_time, pdf_url, audio_url) VALUES
('Bhagavad Gita', 'Vyasa', 'Hinduism', 'sa', 'scripture', 18, 'The Bhagavad Gita is a 700-verse Hindu scripture that is part of the epic Mahabharata. It consists of a conversation between Prince Arjuna and the god Krishna, who serves as his charioteer.', 'A philosophical dialogue between Prince Arjuna and Lord Krishna on duty, righteousness, and the paths to spiritual liberation through karma yoga, bhakti yoga, and jnana yoga.', 'intermediate', 480, 'https://www.holy-bhagavad-gita.org/public/pdf/Bhagavad-Gita.pdf', 'https://example.com/audio/bhagavad-gita'),

('Ramcharitmanas', 'Tulsidas', 'Hinduism', 'hi', 'devotional', 7, 'The Ramcharitmanas is an epic poem in Awadhi composed by the 16th-century Indian poet Tulsidas. It retells the story of Rama as narrated in the ancient Sanskrit Ramayana by Valmiki.', 'The life story of Lord Rama, his exile, the abduction of Sita by Ravana, and the eventual victory of good over evil. A masterpiece of devotional literature emphasizing dharma and bhakti.', 'beginner', 900, null, null),

('Guru Granth Sahib', 'Various Sikh Gurus', 'Sikhism', 'pa', 'scripture', 1430, 'The Guru Granth Sahib is the central religious scripture of Sikhism, regarded by Sikhs as the final, sovereign and eternal Guru following the lineage of the ten human gurus of the religion.', 'The holy book of Sikhism containing hymns and teachings of Sikh Gurus and other saints. Emphasizes devotion to one God, equality, and righteous living.', 'intermediate', 1200, null, null),

('Upanishads (Complete)', 'Various Rishis', 'Hinduism', 'sa', 'philosophical', 108, 'The Upanishads are a collection of texts containing some of the central philosophical concepts of Hinduism. They are considered the end part of Vedas and contain the essence of Vedantic philosophy.', 'Ancient philosophical texts exploring the nature of reality, consciousness, and the relationship between the individual soul (Atman) and universal consciousness (Brahman).', 'advanced', 720, null, null),

('Yoga Sutras of Patanjali', 'Patanjali', 'Yoga Philosophy', 'sa', 'philosophical', 4, 'The Yoga Sutras of Patanjali is a collection of 196 Sanskrit sutras on the theory and practice of yoga. It is considered one of the foundational texts of classical yoga philosophy.', 'A systematic presentation of yoga philosophy covering the eight limbs of yoga (Ashtanga), meditation practices, and the path to spiritual liberation through disciplined practice.', 'advanced', 180, null, null),

('Autobiography of a Yogi', 'Paramahansa Yogananda', 'Kriya Yoga', 'en', 'devotional', 49, 'Autobiography of a Yogi is the autobiography of Paramahansa Yogananda first published in 1946. It has been translated into over 50 languages and is regarded as a modern spiritual classic.', 'The life story of Paramahansa Yogananda, his spiritual journey from India to America, encounters with saints and sages, and the introduction of Kriya Yoga to the Western world.', 'beginner', 600, null, null);

-- Insert spiritual content (mantras, prayers, teachings)
INSERT INTO spiritual_content (source_type, content_type, category, title, content, summary, tags, language, difficulty_level, media_url, transcript, audio_pronunciation) VALUES
('scripture', 'text', 'mantra', 'Gayatri Mantra', 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्।', 'The most sacred mantra in Hinduism, invoking the divine light to illuminate our understanding and guide us toward truth.', '["mantra", "gayatri", "sacred", "vedic", "meditation"]', 'sa', 'beginner', 'https://example.com/audio/gayatri-mantra.mp3', 'Om Bhur Bhuvah Svah Tat Savitur Varenyam Bhargo Devasya Dhimahi Dhiyo Yo Nah Prachodayat', 'Om Bhoor Bhu-vah Svah Tat Sa-vi-tur Va-ren-yam Bhar-go De-vas-ya Dhee-ma-hi Dhee-yo Yo Nah Pra-cho-da-yat'),

('scripture', 'text', 'mantra', 'Maha Mantra (Hare Krishna)', 'हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे। हरे राम हरे राम राम राम हरे हरे।', 'The great mantra for deliverance, chanted to invoke the divine names of Krishna and Rama for spiritual purification and consciousness elevation.', '["mantra", "krishna", "hare", "chanting", "bhakti"]', 'sa', 'beginner', 'https://example.com/audio/hare-krishna.mp3', 'Hare Krishna Hare Krishna Krishna Krishna Hare Hare Hare Rama Hare Rama Rama Rama Hare Hare', 'Ha-re Krish-na Ha-re Krish-na Krish-na Krish-na Ha-re Ha-re Ha-re Ra-ma Ha-re Ra-ma Ra-ma Ra-ma Ha-re Ha-re'),

('saint', 'text', 'teaching', 'Vivekananda on Self-Confidence', 'Arise, awake, and stop not until the goal is reached! You have the power within you to achieve anything. Believe in yourself and that power will manifest. The moment I have realized God sitting in the temple of every human body, the moment I stand in reverence before every human being and see God in him - that moment I am free from bondage.', 'Swami Vivekanandas inspiring message about inner strength, self-belief, and recognizing the divine in all beings.', '["self_confidence", "motivation", "spirituality", "inner_strength"]', 'en', 'beginner', null, null, null),

('scripture', 'text', 'prayer', 'Hanuman Chalisa (First Verse)', 'श्रीगुरु चरन सरोज रज निज मनु मुकुरु सुधारि। बरनउं रघुवर बिमल जसु जो दायकु फल चारि।।', 'Opening verse of Hanuman Chalisa, seeking blessings from the Guru and preparing to sing the pure glories of Lord Rama.', '["hanuman", "prayer", "protection", "devotion", "rama"]', 'hi', 'intermediate', 'https://example.com/audio/hanuman-chalisa.mp3', 'Shri Guru Charan Saroj Raj Nij Man Mukur Sudhari Barnau Raghuvar Bimal Jasu Jo Dayak Phal Chari', null),

('scripture', 'text', 'mantra', 'Om Namah Shivaya', 'ॐ नमः शिवाय', 'The five-syllable mantra dedicated to Lord Shiva, meaning "I bow to Shiva" - representing the consciousness within all beings.', '["mantra", "shiva", "meditation", "consciousness", "sacred"]', 'sa', 'beginner', 'https://example.com/audio/om-namah-shivaya.mp3', 'Om Namah Shivaya', 'Om Na-mah Shi-va-ya'),

('scripture', 'text', 'mantra', 'Mool Mantra (Sikh)', 'ਇਕ ਓਅੰਕਾਰ ਸਤਿ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਨਿਰਭਉ ਨਿਰਵੈਰੁ ਅਕਾਲ ਮੂਰਤਿ ਅਜੂਨੀ ਸੈਭੰ ਗੁਰ ਪ੍ਰਸਾਦਿ ॥', 'The fundamental teaching of Sikhism encapsulating the nature of God as described by Guru Nanak - One Creator, Truth, Fearless, Without hatred, Timeless form.', '["sikh", "mool_mantra", "oneness", "truth", "guru_nanak"]', 'pa', 'intermediate', null, 'Ik Onkar Sat Nam Karta Purakh Nirbhau Nirvair Akal Murat Ajuni Saibhan Gur Prasad', null);

-- Insert festival/calendar events data
INSERT INTO calendar_events (title, event_type, date, time, description, significance, rituals, regional_significance, reminder_enabled) VALUES
('Maha Shivratri', 'festival', '2024-03-08', '00:00:00', 'The great night of Lord Shiva, celebrated with fasting, prayers, and night-long vigils at Shiva temples across India.', 'Commemorates the cosmic dance of Shiva and celebrates the marriage of Shiva and Parvati. Devotees seek blessings for spiritual growth and liberation.', '["fasting", "night_vigil", "abhishek", "rudra_path", "meditation"]', '["north_india", "south_india", "pan_india"]', true),

('Ram Navami', 'festival', '2024-04-17', '06:00:00', 'Celebration of the birth of Lord Rama, the seventh avatar of Vishnu, marked by prayers, processions, and readings from the Ramayana.', 'Celebrates the birth of Lord Rama, the ideal king and avatar of dharma. Devotees seek blessings for righteousness and victory over evil.', '["rama_kalyanam", "procession", "ramayana_reading", "bhajan", "charity"]', '["north_india", "ayodhya", "southern_states"]', true),

('Hanuman Jayanti', 'celebration', '2024-04-23', '05:30:00', 'Birth anniversary of Lord Hanuman, celebrated with special prayers, Hanuman Chalisa recitations, and community gatherings.', 'Honors the birth of Hanuman, the devoted follower of Rama. Celebrated for courage, strength, devotion, and protection from evil.', '["hanuman_chalisa", "special_prayers", "prasad_distribution", "strength_prayers"]', '["all_india", "hanuman_temples"]', true),

('Buddha Purnima', 'festival', '2024-05-23', '04:00:00', 'Celebrates the birth, enlightenment, and death of Gautama Buddha. Observed with meditation, prayers, and acts of charity.', 'Triple blessed day marking Buddhas birth, enlightenment under the Bodhi tree, and his passing into Nirvana.', '["meditation", "dharma_talk", "charity", "temple_visit", "buddhist_prayers"]', '["buddhist_regions", "bihar", "maharashtra", "karnataka"]', true),

('Guru Purnima', 'festival', '2024-07-21', '06:00:00', 'Day dedicated to honoring spiritual teachers and gurus. Disciples express gratitude and seek blessings from their gurus.', 'Celebrates the guru-disciple tradition in Indian culture. The day when Ved Vyasa was born, who classified the Vedas.', '["guru_puja", "dakshina_offering", "spiritual_discourse", "guru_bhajan"]', '["all_india", "spiritual_ashrams", "traditional_families"]', true),

('Krishna Janmashtami', 'festival', '2024-08-26', '00:00:00', 'Birth celebration of Lord Krishna with midnight prayers, dance performances, and elaborate decorations.', 'Celebrates the birth of Krishna, the eighth avatar of Vishnu, known for his teachings in the Bhagavad Gita.', '["midnight_prayers", "jhankis", "dahi_handi", "krishna_bhajan", "fasting"]', '["mathura", "vrindavan", "gujarat", "maharashtra"]', true),

('Ganesh Chaturthi', 'festival', '2024-09-07', '06:30:00', 'Festival celebrating Lord Ganesha with elaborate decorations, prayers, and immersion processions lasting 11 days.', 'Honors Ganesha, the remover of obstacles and lord of beginnings. Celebrated for wisdom, prosperity, and success.', '["ganesh_installation", "daily_prayers", "modak_offering", "immersion_procession"]', '["maharashtra", "karnataka", "andhra_pradesh", "tamil_nadu"]', true),

('Navaratri Beginning', 'festival', '2024-10-03', '06:00:00', 'Nine-night festival dedicated to Goddess Durga, celebrated with dance, music, fasting, and devotional activities.', 'Celebrates the divine feminine energy and the victory of Goddess Durga over the demon Mahishasura.', '["garba_dance", "durga_puja", "fasting", "kalash_sthapana", "goddess_prayers"]', '["gujarat", "west_bengal", "north_india", "eastern_states"]', true);

-- Insert achievements data
INSERT INTO achievements (name, description, category, points_required, rarity, badge_icon) VALUES
('First Steps', 'Complete your first spiritual activity', 'beginner', 10, 'common', '👶'),
('Mantra Master', 'Chant 1008 mantras in total', 'practice', 100, 'uncommon', '📿'),
('Streak Keeper', 'Maintain a 7-day spiritual practice streak', 'consistency', 150, 'uncommon', '🔥'),
('Scripture Scholar', 'Read 10 chapters from any scripture', 'study', 200, 'rare', '📚'),
('Temple Devotee', 'Visit 5 different temples (virtually or physically)', 'pilgrimage', 250, 'rare', '🏛️'),
('Saint Seeker', 'Have meaningful conversations with 3 different AI saints', 'wisdom', 300, 'rare', '🧘‍♂️'),
('Community Helper', 'Help other devotees by answering 10 questions', 'service', 400, 'epic', '🤝'),
('Festival Celebrant', 'Participate in 5 major festivals actively', 'celebration', 500, 'epic', '🎉'),
('Meditation Master', 'Complete 100 hours of total meditation', 'practice', 750, 'legendary', '🧘'),
('Dharma Guardian', 'Achieve the highest spiritual level in the app', 'mastery', 1000, 'legendary', '👑');

-- Insert comprehensive Bhakti Shorts data
INSERT INTO bhakti_shorts (title, description, video_url, thumbnail_url, duration_seconds, category, tags, creator_id, featured, approved) VALUES
('Morning Gayatri Mantra', 'Beautiful rendition of the sacred Gayatri Mantra for morning prayers and meditation', 'https://example.com/videos/gayatri-morning.mp4', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&h=200&fit=crop', 180, 'mantra', '["gayatri", "morning", "meditation", "sacred"]', null, true, true),

('Hanuman Chalisa Powerful', 'Energetic and devotional recitation of Hanuman Chalisa for strength and protection', 'https://example.com/videos/hanuman-chalisa.mp4', 'https://images.unsplash.com/photo-1604608672516-f2d24d230d00?w=300&h=200&fit=crop', 240, 'devotional', '["hanuman", "chalisa", "protection", "strength"]', null, true, true),

('Krishna Bhajan Divine', 'Melodious Krishna bhajan that touches the heart and elevates consciousness', 'https://example.com/videos/krishna-bhajan.mp4', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=200&fit=crop', 195, 'bhajan', '["krishna", "bhajan", "devotion", "love"]', null, true, true),

('Shiva Tandav Stotram', 'Powerful recitation of the cosmic dance hymn of Lord Shiva', 'https://example.com/videos/shiva-tandav.mp4', 'https://images.unsplash.com/photo-1554072675-66db59dba46f?w=300&h=200&fit=crop', 210, 'stotram', '["shiva", "tandav", "cosmic", "power"]', null, true, true),

('Om Meditation Guide', 'Guided meditation using the sacred Om sound for inner peace and spiritual growth', 'https://example.com/videos/om-meditation.mp4', 'https://images.unsplash.com/photo-1529693662653-9d480530041b?w=300&h=200&fit=crop', 300, 'meditation', '["om", "meditation", "peace", "spiritual"]', null, false, true),

('Aarti Sangrah', 'Collection of popular evening aartis for temple worship and home prayers', 'https://example.com/videos/aarti-sangrah.mp4', 'https://images.unsplash.com/photo-1548344810-2148fac76af1?w=300&h=200&fit=crop', 270, 'aarti', '["aarti", "evening", "prayers", "temple"]', null, true, true),

('Bhagavad Gita Wisdom', 'Key teachings from the Bhagavad Gita explained in simple terms for modern seekers', 'https://example.com/videos/gita-wisdom.mp4', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=200&fit=crop', 420, 'teaching', '["gita", "wisdom", "teaching", "philosophy"]', null, true, true),

('Satsang Highlights', 'Inspiring moments from recent spiritual gatherings and satsang sessions', 'https://example.com/videos/satsang-highlights.mp4', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&h=200&fit=crop', 350, 'satsang', '["satsang", "gathering", "inspiration", "community"]', null, false, true);

-- Insert community posts sample data  
INSERT INTO community_posts (user_id, content, post_type, tags, visibility, featured) VALUES
(gen_random_uuid(), 'Just completed my 21-day Gayatri Mantra challenge! The transformation in my daily meditation practice has been incredible. The ancient wisdom truly works when practiced with devotion. 🕉️ #GayatriMantra #SpiritualJourney #Meditation', 'text', '["mantra", "challenge", "meditation", "transformation"]', 'public', true),
(gen_random_uuid(), 'Visited the beautiful Kedarnath temple last weekend. The energy there is absolutely divine! Sharing some photos from my pilgrimage. The journey was challenging but so worth it for the darshan of Bholenath. 🙏 #Kedarnath #Pilgrimage #Shiva #Blessings', 'image', '["pilgrimage", "kedarnath", "shiva", "temple"]', 'public', false),
(gen_random_uuid(), 'Question for fellow devotees: What is your favorite time to chant the Hanuman Chalisa? I find early morning before sunrise gives me the most peace and energy for the day. Would love to hear your experiences! #HanumanChalisa #Devotion #MorningPrayers', 'question', '["hanuman_chalisa", "devotion", "morning_prayers", "question"]', 'public', false),
(gen_random_uuid(), 'Learned this beautiful Krishna bhajan today. The melody just flows from the heart! Music truly is the language of devotion. Radhe Radhe! 🎵 #KrishnaBhajan #Devotion #Music #Radhe', 'audio', '["krishna", "bhajan", "music", "devotion"]', 'public', true);