-- Insert scriptures data
INSERT INTO scriptures (title, author, tradition, language, type, total_chapters, description, summary, difficulty_level, estimated_reading_time, pdf_url, audio_url) VALUES
('Bhagavad Gita', 'Vyasa', 'Hinduism', 'sa', 'scripture', 18, 'The Bhagavad Gita is a 700-verse Hindu scripture that is part of the epic Mahabharata. It consists of a conversation between Prince Arjuna and the god Krishna, who serves as his charioteer.', 'A philosophical dialogue between Prince Arjuna and Lord Krishna on duty, righteousness, and the paths to spiritual liberation through karma yoga, bhakti yoga, and jnana yoga.', 'intermediate', 480, 'https://www.holy-bhagavad-gita.org/public/pdf/Bhagavad-Gita.pdf', 'https://example.com/audio/bhagavad-gita'),
('Ramcharitmanas', 'Tulsidas', 'Hinduism', 'hi', 'devotional', 7, 'The Ramcharitmanas is an epic poem in Awadhi composed by the 16th-century Indian poet Tulsidas. It retells the story of Rama as narrated in the ancient Sanskrit Ramayana by Valmiki.', 'The life story of Lord Rama, his exile, the abduction of Sita by Ravana, and the eventual victory of good over evil. A masterpiece of devotional literature emphasizing dharma and bhakti.', 'beginner', 900, null, null),
('Guru Granth Sahib', 'Various Sikh Gurus', 'Sikhism', 'pa', 'scripture', 1430, 'The Guru Granth Sahib is the central religious scripture of Sikhism, regarded by Sikhs as the final, sovereign and eternal Guru following the lineage of the ten human gurus of the religion.', 'The holy book of Sikhism containing hymns and teachings of Sikh Gurus and other saints. Emphasizes devotion to one God, equality, and righteous living.', 'intermediate', 1200, null, null),
('Upanishads (Complete)', 'Various Rishis', 'Hinduism', 'sa', 'philosophical', 108, 'The Upanishads are a collection of texts containing some of the central philosophical concepts of Hinduism. They are considered the end part of Vedas and contain the essence of Vedantic philosophy.', 'Ancient philosophical texts exploring the nature of reality, consciousness, and the relationship between the individual soul (Atman) and universal consciousness (Brahman).', 'advanced', 720, null, null),
('Yoga Sutras of Patanjali', 'Patanjali', 'Yoga Philosophy', 'sa', 'philosophical', 4, 'The Yoga Sutras of Patanjali is a collection of 196 Sanskrit sutras on the theory and practice of yoga. It is considered one of the foundational texts of classical yoga philosophy.', 'A systematic presentation of yoga philosophy covering the eight limbs of yoga (Ashtanga), meditation practices, and the path to spiritual liberation through disciplined practice.', 'advanced', 180, null, null),
('Autobiography of a Yogi', 'Paramahansa Yogananda', 'Kriya Yoga', 'en', 'devotional', 49, 'Autobiography of a Yogi is the autobiography of Paramahansa Yogananda first published in 1946. It has been translated into over 50 languages and is regarded as a modern spiritual classic.', 'The life story of Paramahansa Yogananda, his spiritual journey from India to America, encounters with saints and sages, and the introduction of Kriya Yoga to the Western world.', 'beginner', 600, null, null);

-- Insert spiritual content using correct enum values (devotional category)
INSERT INTO spiritual_content (source_type, content_type, category, title, content, summary, tags, language, difficulty_level, media_url, transcript, audio_pronunciation) VALUES
('scripture', 'text', 'devotional', 'Gayatri Mantra', 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्।', 'The most sacred mantra in Hinduism, invoking the divine light to illuminate our understanding and guide us toward truth.', '["mantra", "gayatri", "sacred", "vedic", "meditation"]', 'sa', 'beginner', 'https://example.com/audio/gayatri-mantra.mp3', 'Om Bhur Bhuvah Svah Tat Savitur Varenyam Bhargo Devasya Dhimahi Dhiyo Yo Nah Prachodayat', 'Om Bhoor Bhu-vah Svah Tat Sa-vi-tur Va-ren-yam Bhar-go De-vas-ya Dhee-ma-hi Dhee-yo Yo Nah Pra-cho-da-yat'),
('scripture', 'text', 'devotional', 'Maha Mantra (Hare Krishna)', 'हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे। हरे राम हरे राम राम राम हरे हरे।', 'The great mantra for deliverance, chanted to invoke the divine names of Krishna and Rama for spiritual purification and consciousness elevation.', '["mantra", "krishna", "hare", "chanting", "bhakti"]', 'sa', 'beginner', 'https://example.com/audio/hare-krishna.mp3', 'Hare Krishna Hare Krishna Krishna Krishna Hare Hare Hare Rama Hare Rama Rama Rama Hare Hare', 'Ha-re Krish-na Ha-re Krish-na Krish-na Krish-na Ha-re Ha-re Ha-re Ra-ma Ha-re Ra-ma Ra-ma Ra-ma Ha-re Ha-re'),
('saint', 'text', 'teaching', 'Vivekananda on Self-Confidence', 'Arise, awake, and stop not until the goal is reached! You have the power within you to achieve anything. Believe in yourself and that power will manifest. The moment I have realized God sitting in the temple of every human body, the moment I stand in reverence before every human being and see God in him - that moment I am free from bondage.', 'Swami Vivekanandas inspiring message about inner strength, self-belief, and recognizing the divine in all beings.', '["self_confidence", "motivation", "spirituality", "inner_strength"]', 'en', 'beginner', null, null, null),
('scripture', 'text', 'devotional', 'Hanuman Chalisa (First Verse)', 'श्रीगुरु चरन सरोज रज निज मनु मुकुरु सुधारि। बरनउं रघुवर बिमल जसु जो दायकु फल चारि।।', 'Opening verse of Hanuman Chalisa, seeking blessings from the Guru and preparing to sing the pure glories of Lord Rama.', '["hanuman", "prayer", "protection", "devotion", "rama"]', 'hi', 'intermediate', 'https://example.com/audio/hanuman-chalisa.mp3', 'Shri Guru Charan Saroj Raj Nij Man Mukur Sudhari Barnau Raghuvar Bimal Jasu Jo Dayak Phal Chari', null),
('scripture', 'text', 'devotional', 'Om Namah Shivaya', 'ॐ नमः शिवाय', 'The five-syllable mantra dedicated to Lord Shiva, meaning "I bow to Shiva" - representing the consciousness within all beings.', '["mantra", "shiva", "meditation", "consciousness", "sacred"]', 'sa', 'beginner', 'https://example.com/audio/om-namah-shivaya.mp3', 'Om Namah Shivaya', 'Om Na-mah Shi-va-ya'),
('scripture', 'text', 'devotional', 'Mool Mantra (Sikh)', 'ਇਕ ਓਅੰਕਾਰ ਸਤਿ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਨਿਰਭਉ ਨਿਰਵੈਰੁ ਅਕਾਲ ਮੂਰਤਿ ਅਜੂਨੀ ਸੈਭੰ ਗੁਰ ਪ੍ਰਸਾਦਿ ॥', 'The fundamental teaching of Sikhism encapsulating the nature of God as described by Guru Nanak - One Creator, Truth, Fearless, Without hatred, Timeless form.', '["sikh", "mool_mantra", "oneness", "truth", "guru_nanak"]', 'pa', 'intermediate', null, 'Ik Onkar Sat Nam Karta Purakh Nirbhau Nirvair Akal Murat Ajuni Saibhan Gur Prasad', null),
('scripture', 'audio', 'devotional', 'Aarti Collection', 'Collection of traditional evening aartis including Ganga Aarti, Shiva Aarti, and Krishna Aarti for daily worship.', 'Traditional evening prayers sung in temples and homes to honor various deities with light offerings.', '["aarti", "evening", "prayers", "temple", "devotion"]', 'hi', 'beginner', 'https://example.com/audio/aarti-collection.mp3', null, null),
('scripture', 'audio', 'devotional', 'Bhajan Sangrah', 'Collection of devotional songs dedicated to various deities including Krishna bhajans, Shiva bhajans, and Rama bhajans.', 'Melodious devotional songs that elevate consciousness and create spiritual atmosphere for prayer and meditation.', '["bhajan", "devotional", "music", "krishna", "shiva", "rama"]', 'hi', 'beginner', 'https://example.com/audio/bhajan-sangrah.mp3', null, null);