-- Add more sample temple data with rich details
INSERT INTO temples (
  name,
  location,
  primary_deity,
  tradition,
  description,
  history,
  visiting_hours,
  contact_info,
  live_darshan_url,
  darshan_schedule,
  facilities,
  entrance_fee,
  image_urls,
  rating,
  verified,
  youtube_channel_id
) VALUES
(
  'Tirumala Venkateswara Temple',
  '{"lat": 13.6833, "lng": 79.3472, "address": "Tirumala, Tirupati", "city": "Tirupati", "state": "Andhra Pradesh", "country": "India", "pincode": "517504"}'::jsonb,
  'Lord Venkateswara (Vishnu)',
  'Vaishnavism',
  'One of the richest and most visited religious sites in the world, Lord Venkateswara Temple at Tirumala receives millions of devotees yearly.',
  'The temple has a rich history of over 1000 years. Built in Dravidian architecture, it stands as a magnificent example of South Indian temple construction. Legend says Lord Vishnu appeared here to save mankind from Kali Yuga.',
  '{"weekdays": "2:30 AM - 1:00 AM", "weekends": "2:30 AM - 1:00 AM", "special_days": "Open 24 hours during major festivals"}'::jsonb,
  '{"phone": "+91-877-2277777", "email": "complaints@tirumala.org", "website": "https://www.tirumala.org"}'::jsonb,
  'https://www.youtube.com/watch?v=EXAMPLE_TIRUPATI_LIVE',
  '{"suprabhatam": "3:00 AM", "thomala_seva": "5:00 AM", "archana": "6:30 AM - 1:00 PM", "ekantha_seva": "1:30 AM"}'::jsonb,
  '["Free Annadanam", "Accommodation", "Medical Facilities", "Special Darshan", "VIP Darshan", "Parking", "Wheelchair Access"]'::jsonb,
  '{"general": "Free", "special_darshan": "300 INR", "vip_darshan": "500 INR", "seva": "Varies"}'::jsonb,
  '["https://images.unsplash.com/photo-1582632304689-e5c3f3ca3379?w=800", "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800"]'::jsonb,
  4.9,
  true,
  'TTDChannel'
),
(
  'Golden Temple (Harmandir Sahib)',
  '{"lat": 31.6200, "lng": 74.8765, "address": "Golden Temple Road", "city": "Amritsar", "state": "Punjab", "country": "India", "pincode": "143006"}'::jsonb,
  'Guru Granth Sahib',
  'Sikhism',
  'The holiest Gurdwara of Sikhism, known for its stunning golden architecture and spiritual atmosphere. Open to people of all faiths.',
  'Built by Guru Arjan Dev in 1604, the Golden Temple symbolizes universal brotherhood and equality. The temple sits in the middle of a sacred pool (Amrit Sarovar) and is covered with gold leaf, creating a breathtaking reflection.',
  '{"everyday": "Open 24 hours, 7 days a week"}'::jsonb,
  '{"phone": "+91-183-2553957", "email": "sgpc@goldentemple.org", "website": "https://www.goldentemple.org"}'::jsonb,
  'https://www.youtube.com/watch?v=EXAMPLE_GOLDEN_TEMPLE_LIVE',
  '{"morning_prayer": "3:00 AM", "evening_prayer": "6:00 PM", "night_prayer": "9:00 PM", "continuous_kirtan": "24/7"}'::jsonb,
  '["Free Langar (Meals)", "Free Accommodation", "Medical Aid", "Shoe Storage", "Tourist Information", "Library", "Museum"]'::jsonb,
  '{"entry": "Free", "donations": "Welcome"}'::jsonb,
  '["https://images.unsplash.com/photo-1597475943467-71e1cb8c4dae?w=800", "https://images.unsplash.com/photo-1598967485367-81d0a02f7f5c?w=800"]'::jsonb,
  5.0,
  true,
  'GoldenTempleTV'
),
(
  'Vaishno Devi Temple',
  '{"lat": 33.0305, "lng": 74.9499, "address": "Vaishno Devi Bhawan", "city": "Katra", "state": "Jammu and Kashmir", "country": "India", "pincode": "182301"}'::jsonb,
  'Mata Vaishno Devi',
  'Shaktism',
  'Sacred hilltop temple dedicated to Goddess Vaishno Devi, one of the most revered Hindu pilgrimage sites. Requires a 13 km trek from base camp.',
  'Legend says Mata Vaishno Devi took refuge in a cave on Trikuta Hills to meditate. The temple in the cave has natural rock formations representing three forms of Goddess - Mahakali, Mahalakshmi, and Mahasaraswati.',
  '{"darshan": "5:00 AM - 12:00 AM", "trek_hours": "24/7 open"}'::jsonb,
  '{"phone": "+91-1991-234008", "email": "ceovdbsb@jk.gov.in", "website": "https://www.maavaishnodevi.org"}'::jsonb,
  'https://www.youtube.com/watch?v=EXAMPLE_VAISHNO_DEVI',
  '{"morning_aarti": "5:00 AM", "evening_aarti": "7:00 PM"}'::jsonb,
  '["Helicopter Service", "Pony Rides", "Palanquin Service", "Free Medical Aid", "Cloakroom", "Battery Cars", "Prasad Counters", "Accommodation"]'::jsonb,
  '{"entry": "Free", "helicopter": "2000 INR one way", "pony": "1000 INR", "palanquin": "Varies"}'::jsonb,
  '["https://images.unsplash.com/photo-1598967485367-81d0a02f7f5c?w=800"]'::jsonb,
  4.8,
  true,
  'VaishnoDevi'
),
(
  'Jagannath Temple Puri',
  '{"lat": 19.8048, "lng": 85.8314, "address": "Bada Danda", "city": "Puri", "state": "Odisha", "country": "India", "pincode": "752001"}'::jsonb,
  'Lord Jagannath (Krishna)',
  'Vaishnavism',
  'One of the four sacred Char Dham pilgrimage sites. Famous for the annual Rath Yatra festival where massive chariots carry the deities through the streets.',
  'The temple dates back to 1161 CE, built by King Anantavarman Chodaganga. The temple has a unique tradition where the deities are made of wood and renewed every 12-19 years in a secret ceremony. Non-Hindus are not permitted inside.',
  '{"everyday": "5:00 AM - 11:00 PM"}'::jsonb,
  '{"phone": "+91-6752-222002", "website": "https://jagannath.nic.in"}'::jsonb,
  '',
  '{"mangala_alati": "5:00 AM", "mailam": "6:00 AM", "madhyahna_dhupa": "12:00 PM", "sandhya_dhupa": "7:00 PM"}'::jsonb,
  '["Annadanam", "Parking", "Prasad Counter", "Accommodation (nearby)", "Wheelchair Access"]'::jsonb,
  '{"entry": "Free", "special_seva": "Varies"}'::jsonb,
  '["https://images.unsplash.com/photo-1582632304689-e5c3f3ca3379?w=800"]'::jsonb,
  4.7,
  true,
  ''
),
(
  'Meenakshi Amman Temple',
  '{"lat": 9.9195, "lng": 78.1193, "address": "Madurai Main", "city": "Madurai", "state": "Tamil Nadu", "country": "India", "pincode": "625001"}'::jsonb,
  'Goddess Meenakshi and Lord Sundareswarar',
  'Shaivism',
  'Historic Hindu temple with towering gopurams (gateway towers) covered in colorful sculptures. A masterpiece of Dravidian architecture with intricate carvings.',
  'The temple dates back to the 6th century with major reconstruction in the 16th-17th centuries. It has 14 magnificent gopurams, with the tallest reaching 52 meters. The temple complex spans 45 acres and contains 33,000 sculptures.',
  '{"everyday": "5:00 AM - 12:30 PM, 4:00 PM - 9:30 PM"}'::jsonb,
  '{"phone": "+91-452-2345777", "website": "https://www.maduraimeenakshi.org"}'::jsonb,
  'https://www.youtube.com/watch?v=EXAMPLE_MEENAKSHI',
  '{"morning_puja": "6:00 AM", "kalasandhi_puja": "9:00 AM", "evening_puja": "6:00 PM"}'::jsonb,
  '["Audio Guide", "Photography (courtyard only)", "Temple Museum", "Parking", "Prasad Counter", "Shopping Complex"]'::jsonb,
  '{"indians": "50 INR", "foreigners": "500 INR", "camera": "50 INR"}'::jsonb,
  '["https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800"]'::jsonb,
  4.8,
  true,
  'MeenakshiTemple'
),
(
  'Somnath Temple',
  '{"lat": 20.8880, "lng": 70.4013, "address": "Somnath", "city": "Veraval", "state": "Gujarat", "country": "India", "pincode": "362268"}'::jsonb,
  'Lord Shiva',
  'Shaivism',
  'One of the twelve Jyotirlinga temples, Somnath stands majestically on the shores of the Arabian Sea. Known as the "Eternal Shrine" for being rebuilt multiple times through history.',
  'First built in ancient times, destroyed and rebuilt 6 times. The current structure was completed in 1951 in the Chalukya style of architecture. It symbolizes the enduring faith and resilience of Hindu culture.',
  '{"everyday": "6:00 AM - 9:00 PM"}'::jsonb,
  '{"phone": "+91-2876-231302", "website": "https://www.somnath.org"}'::jsonb,
  'https://www.youtube.com/watch?v=EXAMPLE_SOMNATH',
  '{"morning_aarti": "7:00 AM", "noon_aarti": "12:00 PM", "evening_aarti": "7:00 PM", "sound_light_show": "8:00 PM (seasonal)"}'::jsonb,
  '["Light and Sound Show", "Beach Access", "Museum", "Library", "Annadanam", "Parking", "Tourist Information"]'::jsonb,
  '{"entry": "Free", "special_darshan": "Varies"}'::jsonb,
  '["https://images.unsplash.com/photo-1598967485367-81d0a02f7f5c?w=800"]'::jsonb,
  4.7,
  true,
  'SomnathTrust'
);

-- Add more sample audio with proper details
INSERT INTO audio_library (
  title,
  artist,
  category,
  duration,
  language,
  audio_url,
  lyrics,
  meaning,
  pronunciation_guide,
  associated_deity,
  occasion,
  difficulty_level,
  rating
) VALUES
(
  'Shri Hanuman Chalisa',
  'Pandit Jasraj',
  'devotional',
  480,
  'hindi',
  'https://example.com/hanuman-chalisa.mp3',
  'दोहा: श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि। बरनउं रघुबर बिमल जसु, जो दायकु फल चारि॥',
  'A forty-verse hymn in praise of Lord Hanuman, composed by Tulsidas. Reciting it brings courage, strength, and divine blessings.',
  'Shree Guru Charan Saroj Raj, Nij Man Mukur Sudhaari',
  'Lord Hanuman',
  '["Tuesday", "Hanuman Jayanti", "Daily Morning"]'::jsonb,
  'beginner',
  4.9
),
(
  'Durga Saptashati Path',
  'Anuradha Paudwal',
  'mantra',
  2700,
  'sanskrit',
  'https://example.com/durga-saptashati.mp3',
  'ॐ ऐं ह्रीं क्लीं चामुण्डायै विच्चे। नमो देव्यै महादेव्यै शिवायै सततं नमः।',
  'Sacred text of 700 verses glorifying Goddess Durga. Recited during Navratri and for divine protection.',
  'Om Aim Hreem Kleem Chamundayai Vichche',
  'Goddess Durga',
  '["Navratri", "Durga Puja", "Fridays"]'::jsonb,
  'advanced',
  5.0
),
(
  'Morning Aarti - Om Jai Jagdish Hare',
  'Hariharan',
  'aarti',
  300,
  'hindi',
  'https://example.com/om-jai-jagdish.mp3',
  'ॐ जय जगदीश हरे, स्वामी जय जगदीश हरे। भक्त जनों के संकट, दास जनों के संकट, क्षण में दूर करे॥',
  'Universal morning aarti praising the Supreme Lord, bringing peace and prosperity to the household.',
  'Om Jai Jagdeesh Hare, Swami Jai Jagdeesh Hare',
  'Lord Vishnu',
  '["Daily Morning", "All Festivals", "Puja Ceremonies"]'::jsonb,
  'beginner',
  4.8
),
(
  'Guided Meditation - Inner Peace',
  'Spiritual Master Anand',
  'meditation',
  900,
  'english',
  'https://example.com/inner-peace-meditation.mp3',
  '',
  'A 15-minute guided meditation to find inner peace, reduce stress, and connect with your higher self through breath awareness and mindfulness.',
  '',
  '',
  '["Daily Practice", "Stress Relief", "Spiritual Growth"]'::jsonb,
  'beginner',
  4.7
),
(
  'Shiv Tandav Stotram',
  'Shankar Mahadevan',
  'stotram',
  420,
  'sanskrit',
  'https://example.com/shiv-tandav.mp3',
  'जटा टवी गलज्जल प्रवाह पावितस्थले। गलेऽवलम्ब्य लम्बितां भुजङ्ग तुङ्ग मालिकाम्।',
  'Powerful hymn describing Lord Shiva''s cosmic dance, composed by Ravana. Invokes strength, courage, and spiritual energy.',
  'Jata Tavee Galajjala Pravaha Pavitasthale',
  'Lord Shiva',
  '["Maha Shivaratri", "Mondays", "Shravan Month"]'::jsonb,
  'intermediate',
  4.9
);